logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
    com:
      creatorhub: DEBUG

spring:
  config:
    import: optional:file:creatorhub-dev.env[.properties]
  application:
    name: creatorhub-server
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: '20'
        order_updates: 'true'
        order_inserts: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      # host: redis   # Spring Boot Docker 컨테이너 + Redis 도커
      host: localhost   # Spring Boot IDE에서 실행 + Redis 도커
      port: 6379
      # password: 설정 안 했으면 생략
      timeout: 2000

server:
  port: '8000'

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-exp-min: ${ACCESS_TOKEN_EXP_MIN}
  refresh-token-exp-days: ${REFRESH_TOKEN_EXP_DAYS}